version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    assignees:
      - mikeng-io
    labels:
      - "type: chore"
      - "area: deps"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    assignees:
      - mikeng-io
    labels:
      - "type: chore"
      - "area: ci"
    commit-message:
      prefix: "chore(ci)"
